footballr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('myteams/', views.teams_index, name='index'),
    path('myteams/<int:team_id>/', views.teams_detail, name='detail'),
    path('myteams/create/', views.TeamCreate.as_view(), name='teams_create'),
    path('myteams/<int:pk>/update/', views.TeamUpdate.as_view(), name='teams_update'),
    path('myteams/<int:pk>/delete/', views.TeamDelete.as_view(), name='teams_delete'),
    path('myteams/<int:team_id>/add_game/', views.add_game, name='add_game'),
    path('myteams/<int:team_id>assoc_player/<int:player_id>/', views.assoc_player, name='assoc_player'),
    path('players/', views.PlayerList.as_view(), name='players_index'),
    path('players/<int:pk>/', views.PlayerDetail.as_view(), name='players_detail'),
    path('players/create/', views.PlayerCreate.as_view(), name='players_create'),
    path('players/<int:pk>/update/', views.PlayerUpdate.as_view(), name='players_update'),
    path('players/<int:pk>/delete/', views.PlayerDelete.as_view(), name='players_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User

# Provides choices 
RESULTS = (
    ('W', 'Win'),
    ('L', 'Loss'),
)
POSITIONS = (
    ('QB', 'Quarterback'),
    ('RB', 'Running Back'),
    ('WR', 'Wide Receiver'),
    ('TE', 'Tight End'),
    ('K', 'Kicker'),
    ('DEF', 'Defense'),
)

class Player(models.Model):
    # Name and nfl_team are char fields
    name = models.CharField(max_length=50)
    # Position is a char field that is a dropdown menu of the POSITIONS variable
    position = models.CharField(
        max_length=3,
        choices=POSITIONS,
        default=[0][0],
        )
    nfl_team = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('players_detail', kwargs={'pk': self.id})

# Team model
class Team(models.Model):
    # Name and league are character fields
    name = models.CharField(max_length=50)
    league = models.CharField(max_length=50)
    players = models.ManyToManyField(Player)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # Says its name
    def __str__(self):
        return self.name

    # Redirects to detail page upon creation of team
    def get_absolute_url(self):
        return reverse('detail', kwargs = {'team_id': self.id})

# Record model
class Record(models.Model):
    # Week is an integer field and result is a char field that utilizes a dropdown menu
    week = models.IntegerField()
    result = models.CharField(
        max_length=1,
        choices=RESULTS,
        default=RESULTS[0][0],
        )
    # Links the foreign key (team primary key)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    
    # Makes it say its name
    def __str__(self):
        return f"{self.get_result_display()} on Week {self.week}"

    # Changes the default sort
    class Meta:
        ordering = ['week']

main_app/forms.py
from django.forms import ModelForm
from .models import Record

class RecordForm(ModelForm):
    class Meta:
        model = Record
        fields = ['week', 'result']

main_app/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import RecordForm

from .models import Player, Record, Team

# Create your views here.
# Renders the home page by connecting to the home.html template
def home(request):
    return render(request, 'home.html')

# Renders the about page by connecting to the about.html template
def about(request):
    return render(request, 'about.html')

# Renders the my teams page by connecting to the template
@login_required
def teams_index(request):
    # Assigns a variable to the entire Team model object
    teams = Team.objects.filter(user=request.user)
    # Renders the type of request, routes to the teams template, and passes the variable we made into the template to be used
    return render(request, 'teams/index.html', {'teams': teams})

# Renders the team detail (show) page by connecting to the template
@login_required
def teams_detail(request, team_id):
    # Creates a win and loss variable to be used
    wins = 0
    losses = 0
    # Assings the team variable to a specific id in the Team model object that is passed as an argument
    team = Team.objects.get(id=team_id)
    # Attaches a variable to the record model and its objects
    records = Record.objects.all()
    # Allows for us to use the form in our detail template
    record_form = RecordForm()
    # Get players that are not on team
    players_not_on_team = Player.objects.exclude(id__in = team.players.all().values_list('id'))

    # Goes through the records for the team and tallies wins and losses
    for record in records:
        if record.team_id == team.id:
            if record.result == "W":
                wins += 1
            if record.result == "L":
                losses += 1
        
    # Renders the request, the detail template and passes the team variable through
    return render(request, 'teams/detail.html', {
        'team': team,
        'wins': wins,
        'losses': losses,
        'record_form': record_form,
        'players': players_not_on_team,
        })

@login_required
def add_game(request, team_id):
    # Sets form equal to the post request of a completed game form
    form = RecordForm(request.POST)
    # If the form is valid, we save it, set the id equal to the orignating id and then save it
    if form.is_valid():
        new_game = form.save(commit=False)
        new_game.team_id = team_id
        new_game.save()
    return redirect('detail', team_id=team_id)

# Creates a new team using the Team model and reroutes upon success
class TeamCreate(LoginRequiredMixin, CreateView):
    model = Team
    fields = ('name', 'league')
    success_url = '/myteams/'

    # If Valid Team form is received on submission
    def form_valid(self, form):
        # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user
        # Let the CreateView behave normally
        return super().form_valid(form)

# Updates an existing team
class TeamUpdate(LoginRequiredMixin, UpdateView):
    model = Team
    fields = '__all__'

# Deletes an existing team and reroutes upon success
class TeamDelete(LoginRequiredMixin, DeleteView):
    model = Team
    success_url = '/myteams/'

# Allows the player to be linked to the team
@login_required
def assoc_player(request, team_id, player_id):
    Team.objects.get(id=team_id).players.add(player_id)
    return redirect('detail', team_id=team_id)

# Links model to create template
class PlayerCreate(LoginRequiredMixin, CreateView):
    model = Player
    fields = ('name', 'position', 'nfl_team')

# Links model to update template
class PlayerUpdate(LoginRequiredMixin, UpdateView):
    model = Player
    fields = ('name', 'position', 'nfl_team')

# Links model to delete template
class PlayerDelete(LoginRequiredMixin, DeleteView):
    model = Player
    success_url = '/players'

# Links model with index template
class PlayerList(LoginRequiredMixin, ListView):
    model = Player
    template_name = 'players/index.html'

# Links model with detail template
class PlayerDetail(LoginRequiredMixin, DetailView):
    model = Player
    template_name = 'players/detail.html'

# Signup view
def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how we create a 'user' form object that allows us to use data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>Footballr About Page</h1>
<hr />
<p>Footballr was designed and created by Kyler Marquis. If you would like to learn more or inquire further, you can find him on <a href="https://www.linkedin.com/in/kylermarquis/">LinkedIn</a> and on <a href="https://github.com/CodingJedi12">Github</a></p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Footballr</title>
    <!-- link to materialize css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- link to static css -->
    <link rel="stylesheet" href="{% static 'footballr/style.css' %}" />
</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper #dd2c00 deep-orange accent-4">
                <ul>
                    <li>
                        <a href="/" class="left brand-logo">&nbsp;&nbsp;Footballr</a>
                    </li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'teams_create' %}">Add Team</a></li>
                    <li><a href="{% url 'index' %}">View Teams</a></li>
                    <li><a href="{% url 'players_create' %}">Add Player</a></li>
                    <li><a href="{% url 'players_index' %}">View Players</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer #dd2c00 deep-orange accent-4">
        <div class="right">
            All Rights Reserved, &copy; 2022 Footballr &nbsp;
        </div>
    </footer>
</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Footballr</h1>
<hr />
<h5>Are you a fantasy football fanatic?</h5>
<ul>
    <li> With Footballr, have all of your team information in one place! Whether you are in a single league with some friends or are involved across many leagues, Footballr will work for you.</li>
    <li> Add your teams and track them across any league you desire. You can even keep track of your teams' records! </li>
    <li> Add players to your teams to keep track of your team's roster as well! Footballr is a single stop for all your fantasy needs.</li>
</ul>
{% endblock %}

main_app/templates/main_app/player_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Player</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/player_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<!-- If there is a player, then we can edit player -->
    <h1>Update {{ object.name }}</h1>
{% else %}
<!-- If no player, add one -->
    <h1>Add Player</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn blue" type="submit" value="{% if object %} Update Player {% else %} Add Player {% endif %}">
</form>
<script>
    // Allows us to have a dropdown selection for position
    var selectEl = document.getElementById('id_position');
    M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/main_app/team_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Team</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' team.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/team_form.html
{% extends 'base.html' %} {% block content %}

<!-- Checks to see if there is a team object. If there is, we edit. If not, we create -->
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Team</h1>
{% endif %}

<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_p }}
    </table>
    <input type="submit" value="Submit!" class="btn" />
  </form>

{% endblock %}

main_app/templates/players/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Player</h1>


<div class="card">
        <div class="card-content">
            <span class="card-title">
            <!-- Prints name, position and associated team for each player -->
            <p class="deep-orange-text text-accent-4">Player: {{ player.name }}</p>
            <p class="deep-orange-text text-accent-4">Position: {{ player.position }}</p>
            <p class="deep-orange-text text-accent-4">NFL Team: {{ player.nfl_team}}</p>
            </span>
        </div>
    <div class="card-action">
        <!-- Allows user to update and delete player -->
        <a href="{% url 'players_update' player.id %}" class="navy">Edit</a>
        <a href="{% url 'players_delete' player.id %}" class="navy">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/players/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Players</h1>
<!-- Loops through the players object list -->
{% for player in object_list %}
<div class="card">
    <a href="{% url 'players_detail' player.id %}">
        <div class="card-content">
            <span class="card-title">
                <!-- Prints name, position and associated team for each player -->
                Player: {{ player.name }} </br>
                Position: {{ player.position }} </br>
                NFL Team: {{ player.nfl_team}}
            </span>
        </div>
    </a>
</div>
{% endfor %}


{% endblock %}

main_app/templates/teams/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Team Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <!-- Team name and league -->
                <span class="card-title deep-orange-text text-accent-4">{{ team.name }}</span>
                <p class="deep-orange-text text-accent-4">{{ team.league }}</p>
            </div>
            <div class="card-action">
                <!-- Links to update and delete a team -->
                <a href="{% url 'teams_update' team.id %}">Edit</a>
                <a href="{% url 'teams_delete' team.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <!-- Upon submission, attacks this url -->
        <form action="{% url 'add_game' team.id %}" method="post">
            {% csrf_token %} {{ record_form.as_p }}
            <input type="submit" class="btn" value="Add game">
        </form>
        <table class="striped">
          <thead>
            <tr>
                <!-- Keeps track of ongoing record -->
                <th>Record: {{ wins }}-{{ losses }}</th>
            </tr>
            <tr>
              <th>Week</th>
              <th>Win/Loss</th>
            </tr>
          </thead>
          <tbody>
            {% for record in team.record_set.all %}
            <tr>
                <!-- For each instance, prints week and Win/Loss to the page -->
              <td>{{record.week}}</td>
              <td>{{record.get_result_display}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
</div>
<hr />
<div class="row">
    <div class="col s6">
        <h3>{{ team.name }}'s Players</h3>
        <!-- Loops through the players if they are present -->
        {% if team.players.count %} {% for player in team.players.all %}
        <div class="card">
            <a href="{% url 'players_detail' player.id %}">
                <div class="card-content">
                    <span class="card-title">
                        <!-- Prints name, position and associated team to page -->
                        Player: {{ player.name }} </br>
                        Position: {{ player.position }} </br>
                        NFL Team: {{ player.nfl_team}} </br>
                    </span>
                </div>
            </a>
        </div>
        {% endfor %}{% else %}
        <h5>No Players on Roster</h5>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Available Players</h3>
        <!-- If other players exist -->
        {% if players.count %}
            {% for player in players.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                             <!-- Prints name, position and associated team to page -->
                            <p class="deep-orange-text text-accent-4">Player: {{ player.name }}</p>
                            <p class="deep-orange-text text-accent-4">Position: {{ player.position }}</p>
                            <p class="deep-orange-text text-accent-4">NFL Team: {{ player.nfl_team}}</p>
                        </span>
                    </div>
                    <div class="card-action">
                        <!-- Attacks this url upon submission -->
                        <form action="{% url 'assoc_player' team.id player.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn">Add</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        <h5>{{ team.name }} already have all the players available</h5>
        {% endif %}
    </div>
</div>
<script>
    // Selects the result and allows it to be a dropdown of choices
    var selectEl = document.getElementById('id_result');
    M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/teams/index.html
{% extends 'base.html' %} {% block content %}

<h1>Your Teams</h1>

{% for team in teams %}
<div class="card">
    <a href="{% url 'detail' team.id %}">
        <div class="card-content">
            <span class="card-title">{{ team.name }}</span>
            <p>League: {{ team.league }}</p>
        </div>
    </a>
</div>
{% endfor %}{% endblock %}